### ISSUE TITLE
Google Calendar "sign-in" link unresponsive 

### ISSUE THREAD

**Issue by shrineri** [Ellpeck/ObsidianCustomFrames#95] opened 2023-07-28 23:44 UTC
This could very well be user error...

I am on MacOS Ventura 13.4, using Obsidian 1.3.5 on the Desktop. I just downloaded Custom Frames and am trying to use the preset Google Calendar option. It pops up correctly showing the "Google Workspace" log in page, but when I click "Sign-in" or any other link it doesn't work. Is there a setting I need to change to allow this to process, or is this an issue?

**Comment by Ellpeck** [comment] 2023-07-29 08:04
Hi! This is a duplicate of #40 and #76. There are a lot of additional issues linked there with more information, but in general, you want to create a temporary frame that opens the Google login page directly, log in there, remove the temporary frame, and then you're good!

**Closed by Ellpeck** 2023-07-29 08:04 UTC
