### ISSUE TITLE
I can't use Copy button.

### ISSUE THREAD

**Issue by choies1** [Ellpeck/ObsidianCustomFrames#121] opened 2024-04-06 06:26 UTC
I use Caude 3 using customframes.

I can use other buttons. But I can't use Copy button.

Please check it.

![image](https://github.com/Ellpeck/ObsidianCustomFrames/assets/10408785/0f18bd25-3888-4c4f-9e55-6a9c1dfebc38)

**Comment by Ellpeck** [comment] 2024-04-06 07:19
This is a duplicate of #98

**Closed by Ellpeck** 2024-04-06 07:19 UTC

**Comment by nevertoday** [comment] 2024-12-20 10:57
+1
