### ISSUE TITLE
Obsidian needs to use the new app to open the About link

### ISSUE THREAD

**Issue by zhl111** [Ellpeck/ObsidianCustomFrames#47] opened 2022-07-21 16:15 UTC
Click on the embedded web link and a prompt pops up, but there is no alternative program to open the link. Can this be solved?
![image](https://user-images.githubusercontent.com/29135984/180262463-851d8bb2-967a-4680-bc2f-d45f250a82d5.png)

**Comment by Ellpeck** [comment] 2022-08-04 11:24
Duplicate of #40

**Closed by Ellpeck** 2022-08-04 11:24 UTC
