### ISSUE TITLE
sliding divider

### ISSUE THREAD

**Issue by MicheleDeZen** [Ellpeck/ObsidianCustomFrames#20] opened 2022-04-08 11:29 UTC
I am having some problem when i have a custom frame opened on the right side bar and i try to "slide" that side bar bigger or smaller and the "wall" gets stuck attouched to the cursor untill i click it again somewhere.

**Comment by Ellpeck** [comment] 2022-04-08 11:41
This is somewhat of a duplicate of #19. Obsidian currently has an issue where moving the mouse over an embedded webview or iframe makes it get stuck, so the easiest solution is to either scroll really really slowly, or to increase the padding. You can revert the padding to your desired value once you're happy with your layout, of course.

**Closed by Ellpeck** 2022-04-08 11:41 UTC
