### ISSUE TITLE
How can i switch my Google account?

### ISSUE THREAD

**Issue by Diane-Best** [Ellpeck/ObsidianCustomFrames#133] opened 2024-09-02 06:25 UTC
I've encountered a problem when trying to switch between different Google accounts on various websites. After logging in with one Google account on a site, I'm unable to log out and switch to another Google account without manually entering the credentials again. This seems to be due to the caching of the initial account's information.

Steps to Reproduce:

Visit a website that supports Google account login.
Log in using Google account A.
Attempt to switch to Google account B without logging out of account A.
Notice that the system does not provide an option to switch accounts and instead requires re-entering the credentials.

**Comment by Diane-Best** [comment] 2024-09-03 00:11
There is an alternative way to fix it.

1. Launch Google Calendar within the preset frame.
2. Create a new account, "B."
3. Access the custom website and log in using Account B.

**Comment by endrinar** [comment] 2024-11-08 12:50
I have a similar issue. 

I'm currently signed in to both accounts. 
1. Launch Google Calendar within the preset frame. 
<img width="948" alt="image" src="https://github.com/user-attachments/assets/be16e00d-9c52-4b39-978e-89f64dad1c31">

2. Click the second account that I'd like to switch to. It opens up google calendar in my browser and not in the frame.

Since the switch opens a new browser window, I don't have any way to switch between accounts in the frame itself.

**Comment by Ellpeck** [comment] 2024-11-22 21:38
Hi! All custom frames are part of the same "browser", since the entirety of Obsidian is really just a single browser. This means that all login information is shared. If you just generally can't log out of, or into, a Google account, it looks like this might be a duplicate of #40 and various issues linked from there :)

**Closed by Ellpeck** 2024-11-22 21:38 UTC
