### ISSUE TITLE
How to log in to Google Calendar?

### ISSUE THREAD

**Issue by ltroj** [Ellpeck/ObsidianCustomFrames#73] opened 2023-03-26 19:15 UTC
Sorry if I'm missing something obvious here.

I'm tring to display google cal via the CustomFrames plugin.

When trying to log into my google account the system's default browser opens. I can login there but that doesn't do anything within Obsidian. Should the login page open within the CustomFrames pane? Any settings I have to manage to do so?

Thanks!

**Comment by Ellpeck** [comment] 2023-03-26 22:31
This is a duplicate of #40. You might have to go to the regular Google login page in your frame first so that you're able to log in without a popup.

**Closed by Ellpeck** 2023-03-26 22:31 UTC
