### ISSUE TITLE
Links Not Opening from Within Custom Frames

### ISSUE THREAD

**Issue by julroger2013** [Ellpeck/ObsidianCustomFrames#76] opened 2023-04-08 19:10 UTC
I use Custom Frames to embed specific projects from inside Todoist in my sidebar. 

I've noticed that any links I place within Todoist (for example a link inside a Todoist task that connects to a particular page in Obsidian) do not work if I click the link from inside the Custom Frame. 

However, if I set the desired Custom Frame to "force iframe," the links then become functional. The downside, of course, is that forcing the iframe mode makes it so that any settings specific to the custom frame (such as custom CSS) don't work. 

Is there any way to get the links functioning from inside the default Custom Frame, rather than needing to force iframe mode instead?

I'm using Windows 10, if that's relevant, although I haven't noticed different performance between my Windows PC and my MacBook.

**Comment by 1977878681** [comment] 2023-05-18 16:44
This same situation, but first thank the creator for his efforts, niubi!!!

**Comment by Ellpeck** [comment] 2023-05-26 11:37
Talking about this issue to @lishid, we realized that it also occurs in sites embedded into Canvas, and appears to be caused by the way that Electron's webviews are set up on Obsidian's side. Unfortuantely, changing these settings comes with potential security concerns that would have to be inspected further and possibly addressed, which is why there's not a fix for this issue yet.

**Comment by Ellpeck** [comment] 2023-07-04 18:30
This issue has been fixed in Obsidian 1.3.7!

**Closed by Ellpeck** 2023-07-04 18:30 UTC
Labels: bug
