### ISSUE TITLE
Copy button in Newbing answer doesn't work

### ISSUE THREAD

**Issue by wwjCMP** [Ellpeck/ObsidianCustomFrames#110] opened 2024-01-10 12:35 UTC
https://www.bing.com/search?q=Bing+AI&showconv=1&ntref=1

![image](https://github.com/Ellpeck/ObsidianCustomFrames/assets/32979859/8ca14d84-c24a-428d-b66d-0ed51e1cae70)

**Comment by Ellpeck** [comment] 2024-01-10 16:18
Duplicate of #98

**Closed by Ellpeck** 2024-01-10 16:18 UTC

**Comment by nevertoday** [comment] 2024-12-20 09:46
very sad
