### ISSUE TITLE
Unable to login to Notion due to popups being blocked

### ISSUE THREAD

**Issue by semisenioritis** [Ellpeck/ObsidianCustomFrames#74] opened 2023-03-31 06:13 UTC
Ive been using the preset plugin for notion, but for some reason it seems that notion has updated their ui and now to login with google, you need to enable popups on your browser. 

since obsidian doesnt allow popups, is there any workround to this?

**Comment by semisenioritis** [comment] 2023-03-31 06:15
i tried locating the url link for the popup but couldnt seem to find that either. most probably for security reasons the link must be a default url that then uses the session to redirect you to the Uauth popup

**Comment by Ellpeck** [comment] 2023-03-31 07:32
Hi! This is a duplicate of #40, which also links to a lot of other issues of people having the same problem, as well as possible solutions that they tried!

**Closed by Ellpeck** 2023-03-31 07:32 UTC

**Comment by semisenioritis** [comment] 2023-03-31 07:34
sure, also thanks for the plugin! 
its really usefull! keep up the good work!!
